// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	IDOrder   int32          `json:"id_order"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
	Address   sql.NullString `json:"address"`
	ZipCode   sql.NullString `json:"zip_code"`
	CreatedAt time.Time      `json:"created_at"`
	Modified  time.Time      `json:"modified"`
	Deleted   sql.NullTime   `json:"deleted"`
}

type OrderProduct struct {
	IDOrderProduct int64         `json:"id_order_product"`
	IDOrder        sql.NullInt32 `json:"id_order"`
	IDProduct      sql.NullInt32 `json:"id_product"`
	Qty            int32         `json:"qty"`
	PricePerQty    int32         `json:"price_per_qty"`
	CreatedAt      time.Time     `json:"created_at"`
	Modified       time.Time     `json:"modified"`
	Deleted        sql.NullTime  `json:"deleted"`
}

type Product struct {
	IDProduct int32          `json:"id_product"`
	Name      sql.NullString `json:"name"`
	Stock     int32          `json:"stock"`
	Price     int32          `json:"price"`
	Active    sql.NullBool   `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	Modified  time.Time      `json:"modified"`
	Deleted   sql.NullTime   `json:"deleted"`
}

type User struct {
	IDUser    int32          `json:"id_user"`
	Username  sql.NullString `json:"username"`
	Password  string         `json:"password"`
	Active    sql.NullBool   `json:"active"`
	CreatedAt time.Time      `json:"created_at"`
	Modified  time.Time      `json:"modified"`
	Deleted   sql.NullTime   `json:"deleted"`
}
