// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	DeleteProduct(ctx context.Context, idProduct int32) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	MakeNewProduct(ctx context.Context, arg MakeNewProductParams) (Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	getProduct(ctx context.Context, idProduct int32) (Product, error)
	getProductLowStock(ctx context.Context, stock int32) (Product, error)
}

var _ Querier = (*Queries)(nil)
